import type { StepConfig } from '@/types/scenario'

export const parentOrgSteps: StepConfig[] = [
  { kind: 'GET_WHO_AM_I', title: 'Verify Credentials', description: 'Confirm your API keys are working and inspect your organization.' },
  { kind: 'UPDATE_ORGANIZATION_NAME', title: 'Set Organization Name', description: 'Give your organization a clear name for identification.' },
  { kind: 'SET_ORG_FEATURE', title: 'Enable Org Features', description: 'Enable features your application needs, such as email auth or advanced policies.' },
  { kind: 'CREATE_USER_TAG', title: 'Create User Tag', description: 'Create a tag to classify users in your sub-orgs (e.g. "end-user", "admin").' },
  { kind: 'CREATE_PRIVATE_KEY_TAG', title: 'Create Private Key Tag', description: 'Create a tag to classify private keys (e.g. "hot-wallet", "cold-storage").' },
  { kind: 'CREATE_POLICY', title: 'Create Org Policy', description: 'Create a top-level policy governing signing permissions across your organization.', params: { type: 'permissive' } },
]

export const subOrgSteps: StepConfig[] = [
  { kind: 'CREATE_SUB_ORG', title: 'Create Sub-Organization', description: 'Create a sub-org for your end user. You retain root access during setup.' },
  { kind: 'CREATE_WALLET', title: 'Create Wallet', description: 'Create the primary wallet for this sub-org.' },
  { kind: 'CREATE_POLICY', title: 'Create Sub-Org Policy', description: 'Create a signing policy scoped to this sub-org. References tags from parent org setup.', params: { type: 'permissive' } },
  { kind: 'CREATE_API_USER', title: 'Create API User', description: 'Create an API-only user for server-side access. The end user claims their access via the Turnkey dashboard.' },
]

export const SDK_METHODS: Record<string, string> = {
  CREATE_SUB_ORG: 'createSubOrganization',
  CREATE_WALLET: 'createWallet',
  CREATE_WALLET_ACCOUNTS: 'createWalletAccounts',
  CREATE_API_USER: 'createApiOnlyUsers',
  CREATE_API_KEYS: 'createApiKeys',
  CREATE_PRIVATE_KEY: 'createPrivateKeys',
  CREATE_POLICY: 'createPolicy',
  CREATE_USER_TAG: 'createUserTag',
  CREATE_PRIVATE_KEY_TAG: 'createPrivateKeyTag',
  CREATE_POLICIES: 'createPolicies',
  CREATE_INVITATIONS: 'createInvitations',
  SIGN_TRANSACTION: 'signTransaction',
  SIGN_RAW_PAYLOAD: 'signRawPayload',
  SIGN_RAW_PAYLOADS: 'signRawPayloads',
  UPDATE_WALLET: 'updateWallet',
  UPDATE_POLICY: 'updatePolicy',
  UPDATE_USER: 'updateUser',
  UPDATE_ROOT_QUORUM: 'updateRootQuorum',
  UPDATE_ORGANIZATION_NAME: 'updateOrganizationName',
  SET_ORG_FEATURE: 'setOrganizationFeature',
  REMOVE_ORG_FEATURE: 'removeOrganizationFeature',
  DELETE_POLICY: 'deletePolicy',
  DELETE_WALLETS: 'deleteWallets',
  DELETE_USERS: 'deleteUsers',
  DELETE_PRIVATE_KEYS: 'deletePrivateKeys',
  DELETE_API_KEYS: 'deleteApiKeys',
  DELETE_USER_TAGS: 'deleteUserTags',
  DELETE_PRIVATE_KEY_TAGS: 'deletePrivateKeyTags',
  DELETE_POLICIES: 'deletePolicies',
  GET_WHO_AM_I: 'getWhoAmI',
  GET_WALLET: 'getWallet',
  GET_USER: 'getUser',
  GET_POLICY: 'getPolicy',
  GET_API_KEYS: 'getApiKeys',
  GET_CONFIGS: 'getConfigs',
  GET_PRIVATE_KEY: 'getPrivateKey',
  GET_AUTHENTICATORS: 'getAuthenticators',
  GET_SUB_ORGS: 'getSubOrgIds',
  GET_VERIFIED_SUB_ORGS: 'getVerifiedSubOrgIds',
  LIST_WALLETS: 'getWallets',
  LIST_WALLET_ACCOUNTS: 'getWalletAccounts',
  LIST_USERS: 'getUsers',
  LIST_POLICIES: 'getPolicies',
  LIST_ACTIVITIES: 'getActivities',
  LIST_PRIVATE_KEYS: 'getPrivateKeys',
  LIST_USER_TAGS: 'listUserTags',
  LIST_PRIVATE_KEY_TAGS: 'listPrivateKeyTags',
  LIST_SUPPORTED_ASSETS: 'listSupportedAssets',
}
